name: Generate Progress Report

on:
  schedule:
    - cron: "0 0 * * *" # 每天UTC时间0点运行

jobs:
  generate-progress-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Generate progress report
        run: python scripts/generate_progress_report.py
      - name: Commit and push progress report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add progress/progress_report.json
          git commit -m "Update progress report [skip ci]"
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git
