name: Check Submissions

on:
  pull_request:
    paths:
      - 'tasks/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Task Submission
      run: |
        echo "Checking for task submissions..."
        if [ ! -d "tasks" ]; then
          echo "No tasks submitted!"
          exit 1
        fi
        echo "Tasks found!"
